language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
before_install:
    - npm install -g vuepress@1.0.0-alpha.44
install:
    - npm install vuepress-plugin-export@0.2.0
script:
    - npm run docs:build
    - npm run docs:pdf
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN
    repo: dvalpx/dvalpx.github.io
    keep-history: true
    target-branch: master
    on:
        branch: 5.8_press